using Microsoft.EntityFrameworkCore;
using SaffiraCloud.ApplicationCore.Entities;
using System;

namespace SaffiraCloud.Infra.Data.Extensions
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Pais>()
                .HasData(
                    new Pais { ID = 1, Nome = "Afeganistão", CodigoIBGE = "004", CodigoISO = "AFG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 2, Nome = "África do Sul", CodigoIBGE = "710", CodigoISO = "ZAF", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 3, Nome = "Albânia", CodigoIBGE = "008", CodigoISO = "ALB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 4, Nome = "Alemanha", CodigoIBGE = "276", CodigoISO = "DEU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 5, Nome = "Andorra", CodigoIBGE = "020", CodigoISO = "AND", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 6, Nome = "Angola", CodigoIBGE = "024", CodigoISO = "AGO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 7, Nome = "Anguilla", CodigoIBGE = "660", CodigoISO = "AIA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 8, Nome = "Antígua e Barbuda", CodigoIBGE = "028", CodigoISO = "ATG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 9, Nome = "Arábia Saudita", CodigoIBGE = "682", CodigoISO = "SAU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 10, Nome = "Argélia", CodigoIBGE = "012", CodigoISO = "DZA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 11, Nome = "Argentina", CodigoIBGE = "032", CodigoISO = "ARG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 12, Nome = "Armênia", CodigoIBGE = "051", CodigoISO = "ARM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 13, Nome = "Aruba", CodigoIBGE = "533", CodigoISO = "ABW", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 14, Nome = "Austrália", CodigoIBGE = "036", CodigoISO = "AUS", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 15, Nome = "Áustria", CodigoIBGE = "040", CodigoISO = "AUT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 16, Nome = "Azerbaijão", CodigoIBGE = "031", CodigoISO = "AZE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 17, Nome = "Bahamas", CodigoIBGE = "044", CodigoISO = "BHS", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 18, Nome = "Bangladesh", CodigoIBGE = "050", CodigoISO = "BGD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 19, Nome = "Barbados", CodigoIBGE = "052", CodigoISO = "BRB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 20, Nome = "Barein", CodigoIBGE = "048", CodigoISO = "BHR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 21, Nome = "Bélgica", CodigoIBGE = "056", CodigoISO = "BEL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 22, Nome = "Belize", CodigoIBGE = "084", CodigoISO = "BLZ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 23, Nome = "Benin", CodigoIBGE = "204", CodigoISO = "BEN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 24, Nome = "Bermuda", CodigoIBGE = "060", CodigoISO = "BMU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 25, Nome = "Bielorússia", CodigoIBGE = "112", CodigoISO = "BLR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 26, Nome = "Bolívia", CodigoIBGE = "068", CodigoISO = "BOL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 27, Nome = "Bonaire, Santo Eustáquio e Saba", CodigoIBGE = "535", CodigoISO = "BES", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 28, Nome = "Bósnia-Herzegovina", CodigoIBGE = "070", CodigoISO = "BIH", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 29, Nome = "Botsuana", CodigoIBGE = "072", CodigoISO = "BWA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 30, Nome = "Brasil", CodigoIBGE = "076", CodigoISO = "BRA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 31, Nome = "Brunei", CodigoIBGE = "096", CodigoISO = "BRN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 32, Nome = "Bulgária", CodigoIBGE = "100", CodigoISO = "BGR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 33, Nome = "Burkina Faso", CodigoIBGE = "854", CodigoISO = "BFA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 34, Nome = "Burundi", CodigoIBGE = "108", CodigoISO = "BDI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 35, Nome = "Butão", CodigoIBGE = "064", CodigoISO = "BTN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 36, Nome = "Cabo Verde", CodigoIBGE = "132", CodigoISO = "CPV", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 37, Nome = "Camarões", CodigoIBGE = "120", CodigoISO = "CMR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 38, Nome = "Camboja", CodigoIBGE = "116", CodigoISO = "KHM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 39, Nome = "Canadá", CodigoIBGE = "124", CodigoISO = "CAN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 40, Nome = "Casaquistão", CodigoIBGE = "398", CodigoISO = "KAZ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 41, Nome = "Catar", CodigoIBGE = "634", CodigoISO = "QAT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 42, Nome = "Chade", CodigoIBGE = "148", CodigoISO = "TCD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 43, Nome = "Chile", CodigoIBGE = "152", CodigoISO = "CHL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 44, Nome = "China", CodigoIBGE = "156", CodigoISO = "CHN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 45, Nome = "China, Hong Kong", CodigoIBGE = "344", CodigoISO = "HKG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 46, Nome = "China, Macao", CodigoIBGE = "446", CodigoISO = "MAC", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 47, Nome = "Chipre", CodigoIBGE = "196", CodigoISO = "CYP", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 48, Nome = "Cingapura", CodigoIBGE = "702", CodigoISO = "SGP", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 49, Nome = "Colômbia", CodigoIBGE = "170", CodigoISO = "COL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 50, Nome = "Comores", CodigoIBGE = "174", CodigoISO = "COM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 51, Nome = "Congo", CodigoIBGE = "178", CodigoISO = "COG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 52, Nome = "Coréia do Norte", CodigoIBGE = "408", CodigoISO = "PRK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 53, Nome = "Coréia do Sul", CodigoIBGE = "410", CodigoISO = "KOR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 54, Nome = "Costa do Marfim", CodigoIBGE = "384", CodigoISO = "CIV", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 55, Nome = "Costa Rica", CodigoIBGE = "188", CodigoISO = "CRI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 56, Nome = "Croácia", CodigoIBGE = "191", CodigoISO = "HRV", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 57, Nome = "Cuba", CodigoIBGE = "192", CodigoISO = "CUB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 58, Nome = "Curaçao", CodigoIBGE = "531", CodigoISO = "CUW", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 59, Nome = "Dinamarca", CodigoIBGE = "208", CodigoISO = "DNK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 60, Nome = "Djibouti", CodigoIBGE = "262", CodigoISO = "DJI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 61, Nome = "Dominica", CodigoIBGE = "212", CodigoISO = "DMA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 62, Nome = "Egito", CodigoIBGE = "818", CodigoISO = "EGY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 63, Nome = "El Salvador", CodigoIBGE = "222", CodigoISO = "SLV", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 64, Nome = "Emirados Árabes Unidos", CodigoIBGE = "784", CodigoISO = "ARE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 65, Nome = "Equador", CodigoIBGE = "218", CodigoISO = "ECU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 66, Nome = "Eritréia", CodigoIBGE = "232", CodigoISO = "ERI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 67, Nome = "Eslováquia", CodigoIBGE = "703", CodigoISO = "SVK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 68, Nome = "Eslovênia", CodigoIBGE = "705", CodigoISO = "SVN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 69, Nome = "Espanha", CodigoIBGE = "724", CodigoISO = "ESP", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 70, Nome = "Estados Unidos da América", CodigoIBGE = "840", CodigoISO = "USA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 71, Nome = "Estônia", CodigoIBGE = "233", CodigoISO = "EST", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 72, Nome = "Etiópia", CodigoIBGE = "231", CodigoISO = "ETH", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 73, Nome = "Fiji", CodigoIBGE = "242", CodigoISO = "FJI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 74, Nome = "Filipinas", CodigoIBGE = "608", CodigoISO = "PHL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 75, Nome = "Finlândia", CodigoIBGE = "246", CodigoISO = "FIN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 76, Nome = "França", CodigoIBGE = "250", CodigoISO = "FRA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 77, Nome = "Gabão", CodigoIBGE = "266", CodigoISO = "GAB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 78, Nome = "Gâmbia", CodigoIBGE = "270", CodigoISO = "GMB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 79, Nome = "Gana", CodigoIBGE = "288", CodigoISO = "GHA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 80, Nome = "Geórgia", CodigoIBGE = "268", CodigoISO = "GEO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 81, Nome = "Gibraltar", CodigoIBGE = "292", CodigoISO = "GIB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 82, Nome = "Granada", CodigoIBGE = "308", CodigoISO = "GRD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 83, Nome = "Grécia", CodigoIBGE = "300", CodigoISO = "GRC", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 84, Nome = "Groenlândia", CodigoIBGE = "304", CodigoISO = "GRL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 85, Nome = "Guam", CodigoIBGE = "316", CodigoISO = "GUM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 86, Nome = "Guatemala", CodigoIBGE = "320", CodigoISO = "GTM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 87, Nome = "Guernsey", CodigoIBGE = "831", CodigoISO = "GGY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 88, Nome = "Guiana", CodigoIBGE = "328", CodigoISO = "GUY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 89, Nome = "Guiana Francesa", CodigoIBGE = "254", CodigoISO = "GUF", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 90, Nome = "Guiné", CodigoIBGE = "324", CodigoISO = "GIN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 91, Nome = "Guiné Equatorial", CodigoIBGE = "226", CodigoISO = "GNQ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 92, Nome = "Guiné-Bissau", CodigoIBGE = "624", CodigoISO = "GNB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 93, Nome = "Haiti", CodigoIBGE = "332", CodigoISO = "HTI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 94, Nome = "Holanda", CodigoIBGE = "528", CodigoISO = "NLD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 95, Nome = "Honduras", CodigoIBGE = "340", CodigoISO = "HND", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 96, Nome = "Hungria", CodigoIBGE = "348", CodigoISO = "HUN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 97, Nome = "Iêmen", CodigoIBGE = "887", CodigoISO = "YEM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 98, Nome = "Ilha de Man", CodigoIBGE = "833", CodigoISO = "IMN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 99, Nome = "Ilha Guadalupe", CodigoIBGE = "312", CodigoISO = "GLP", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 100, Nome = "Ilha Norfolk", CodigoIBGE = "574", CodigoISO = "NFK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 101, Nome = "Ilha Reunião", CodigoIBGE = "638", CodigoISO = "REU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 102, Nome = "Ilhas Alanda", CodigoIBGE = "248", CodigoISO = "ALA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 103, Nome = "Ilhas Cayman", CodigoIBGE = "136", CodigoISO = "CYM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 104, Nome = "Ilhas Cook", CodigoIBGE = "184", CodigoISO = "COK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 105, Nome = "Ilhas do Canal", CodigoIBGE = "830", CodigoISO = "", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 106, Nome = "Ilhas Faeroe", CodigoIBGE = "234", CodigoISO = "FRO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 107, Nome = "Ilhas Falkland", CodigoIBGE = "238", CodigoISO = "FLK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 108, Nome = "Ilhas Marianas", CodigoIBGE = "580", CodigoISO = "MNP", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 109, Nome = "Ilhas Marshall", CodigoIBGE = "584", CodigoISO = "MHL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 110, Nome = "Ilhas Salomão", CodigoIBGE = "090", CodigoISO = "SLB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 111, Nome = "Ilhas Turks e Caicos", CodigoIBGE = "796", CodigoISO = "TCA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 112, Nome = "Ilhas Virgens", CodigoIBGE = "850", CodigoISO = "VIR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 113, Nome = "Ilhas Virgens Britânicas", CodigoIBGE = "092", CodigoISO = "VGB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 114, Nome = "Ilhas Wallis e Futuna", CodigoIBGE = "876", CodigoISO = "WLF", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 115, Nome = "Índia", CodigoIBGE = "356", CodigoISO = "IND", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 116, Nome = "Indonésia", CodigoIBGE = "360", CodigoISO = "IDN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 117, Nome = "Irã", CodigoIBGE = "364", CodigoISO = "IRN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 118, Nome = "Iraque", CodigoIBGE = "368", CodigoISO = "IRQ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 119, Nome = "Irlanda", CodigoIBGE = "372", CodigoISO = "IRL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 120, Nome = "Islândia", CodigoIBGE = "352", CodigoISO = "ISL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 121, Nome = "Israel", CodigoIBGE = "376", CodigoISO = "ISR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 122, Nome = "Itália", CodigoIBGE = "380", CodigoISO = "ITA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 123, Nome = "Jamaica", CodigoIBGE = "388", CodigoISO = "JAM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 124, Nome = "Japão", CodigoIBGE = "392", CodigoISO = "JPN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 125, Nome = "Jersey", CodigoIBGE = "832", CodigoISO = "JEY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 126, Nome = "Jordânia", CodigoIBGE = "400", CodigoISO = "JOR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 127, Nome = "Kiribati", CodigoIBGE = "296", CodigoISO = "KIR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 128, Nome = "Kuwait", CodigoIBGE = "414", CodigoISO = "KWT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 129, Nome = "Laos", CodigoIBGE = "418", CodigoISO = "LAO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 130, Nome = "Lesoto", CodigoIBGE = "426", CodigoISO = "LSO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 131, Nome = "Letônia", CodigoIBGE = "428", CodigoISO = "LVA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 132, Nome = "Líbano", CodigoIBGE = "422", CodigoISO = "LBN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 133, Nome = "Libéria", CodigoIBGE = "430", CodigoISO = "LBR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 134, Nome = "Líbia", CodigoIBGE = "434", CodigoISO = "LBY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 135, Nome = "Liechtenstein", CodigoIBGE = "438", CodigoISO = "LIE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 136, Nome = "Lituânia", CodigoIBGE = "440", CodigoISO = "LTU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 137, Nome = "Luxemburgo", CodigoIBGE = "442", CodigoISO = "LUX", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 138, Nome = "Macedônia", CodigoIBGE = "807", CodigoISO = "MKD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 139, Nome = "Madagáscar", CodigoIBGE = "450", CodigoISO = "MDG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 140, Nome = "Malásia", CodigoIBGE = "458", CodigoISO = "MYS", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 141, Nome = "Malauí", CodigoIBGE = "454", CodigoISO = "MWI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 142, Nome = "Maldivas", CodigoIBGE = "462", CodigoISO = "MDV", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 143, Nome = "Mali", CodigoIBGE = "466", CodigoISO = "MLI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 144, Nome = "Malta", CodigoIBGE = "470", CodigoISO = "MLT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 145, Nome = "Marrocos", CodigoIBGE = "504", CodigoISO = "MAR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 146, Nome = "Martinica", CodigoIBGE = "474", CodigoISO = "MTQ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 147, Nome = "Maurício", CodigoIBGE = "480", CodigoISO = "MUS", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 148, Nome = "Mauritânia", CodigoIBGE = "478", CodigoISO = "MRT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 149, Nome = "Mayotte", CodigoIBGE = "175", CodigoISO = "MYT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 150, Nome = "México", CodigoIBGE = "484", CodigoISO = "MEX", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 151, Nome = "Mianma", CodigoIBGE = "104", CodigoISO = "MMR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 152, Nome = "Micronésia", CodigoIBGE = "583", CodigoISO = "FSM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 153, Nome = "Moçambique", CodigoIBGE = "508", CodigoISO = "MOZ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 154, Nome = "Moldávia", CodigoIBGE = "498", CodigoISO = "MDA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 155, Nome = "Mônaco", CodigoIBGE = "492", CodigoISO = "MCO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 156, Nome = "Mongólia", CodigoIBGE = "496", CodigoISO = "MNG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 157, Nome = "Montenegro", CodigoIBGE = "499", CodigoISO = "MNE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 158, Nome = "Montserrat", CodigoIBGE = "500", CodigoISO = "MSR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 159, Nome = "Namíbia", CodigoIBGE = "516", CodigoISO = "NAM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 160, Nome = "Nauru", CodigoIBGE = "520", CodigoISO = "NRU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 161, Nome = "Nepal", CodigoIBGE = "524", CodigoISO = "NPL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 162, Nome = "Nicarágua", CodigoIBGE = "558", CodigoISO = "NIC", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 163, Nome = "Níger", CodigoIBGE = "562", CodigoISO = "NER", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 164, Nome = "Nigéria", CodigoIBGE = "566", CodigoISO = "NGA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 165, Nome = "Niue", CodigoIBGE = "570", CodigoISO = "NIU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 166, Nome = "Noruega", CodigoIBGE = "578", CodigoISO = "NOR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 167, Nome = "Nova Caledônia", CodigoIBGE = "540", CodigoISO = "NCL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 168, Nome = "Nova Zelândia", CodigoIBGE = "554", CodigoISO = "NZL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 169, Nome = "Omã", CodigoIBGE = "512", CodigoISO = "OMN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 170, Nome = "Palau", CodigoIBGE = "585", CodigoISO = "PLW", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 171, Nome = "Palestina", CodigoIBGE = "275", CodigoISO = "PSE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 172, Nome = "Panamá", CodigoIBGE = "591", CodigoISO = "PAN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 173, Nome = "Papua Nova Guiné", CodigoIBGE = "598", CodigoISO = "PNG", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 174, Nome = "Paquistão", CodigoIBGE = "586", CodigoISO = "PAK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 175, Nome = "Paraguai", CodigoIBGE = "600", CodigoISO = "PRY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 176, Nome = "Peru", CodigoIBGE = "604", CodigoISO = "PER", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 177, Nome = "Pitcairn", CodigoIBGE = "612", CodigoISO = "PCN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 178, Nome = "Polinésia Francesa", CodigoIBGE = "258", CodigoISO = "PYF", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 179, Nome = "Polônia", CodigoIBGE = "616", CodigoISO = "POL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 180, Nome = "Porto Rico", CodigoIBGE = "630", CodigoISO = "PRI", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 181, Nome = "Portugal", CodigoIBGE = "620", CodigoISO = "PRT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 182, Nome = "Quênia", CodigoIBGE = "404", CodigoISO = "KEN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 183, Nome = "Quirguistão", CodigoIBGE = "417", CodigoISO = "KGZ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 184, Nome = "Reino Unido", CodigoIBGE = "826", CodigoISO = "GBR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 185, Nome = "República Centro Africana", CodigoIBGE = "140", CodigoISO = "CAF", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 186, Nome = "República Democrática do Congo", CodigoIBGE = "180", CodigoISO = "COD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 187, Nome = "República Dominicana", CodigoIBGE = "214", CodigoISO = "DOM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 188, Nome = "República Tcheca", CodigoIBGE = "203", CodigoISO = "CZE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 189, Nome = "Romênia", CodigoIBGE = "642", CodigoISO = "ROU", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 190, Nome = "Ruanda", CodigoIBGE = "646", CodigoISO = "RWA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 191, Nome = "Rússia (Federação Russa)", CodigoIBGE = "643", CodigoISO = "RUS", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 192, Nome = "Saara Ocidental", CodigoIBGE = "732", CodigoISO = "ESH", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 193, Nome = "Saint Martin (parte francesa)", CodigoIBGE = "663", CodigoISO = "MAF", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 194, Nome = "Saint Martin (parte holandesa)", CodigoIBGE = "534", CodigoISO = "SXM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 195, Nome = "Saint Pierre e Miquelon", CodigoIBGE = "666", CodigoISO = "SPM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 196, Nome = "Samoa", CodigoIBGE = "882", CodigoISO = "WSM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 197, Nome = "Samoa Americana", CodigoIBGE = "016", CodigoISO = "ASM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 198, Nome = "San Marino", CodigoIBGE = "674", CodigoISO = "SMR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 199, Nome = "Santa Helena", CodigoIBGE = "654", CodigoISO = "SHN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 200, Nome = "Santa Lúcia", CodigoIBGE = "662", CodigoISO = "LCA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 201, Nome = "São Bartolomeu", CodigoIBGE = "652", CodigoISO = "BLM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 202, Nome = "São Cristóvão e Nevis", CodigoIBGE = "659", CodigoISO = "KNA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 203, Nome = "São Tome e Príncipe", CodigoIBGE = "678", CodigoISO = "STP", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 204, Nome = "São Vicente e Granadinas", CodigoIBGE = "670", CodigoISO = "VCT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 205, Nome = "Sark", CodigoIBGE = "680", CodigoISO = "", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 206, Nome = "Seichelles", CodigoIBGE = "690", CodigoISO = "SYC", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 207, Nome = "Senegal", CodigoIBGE = "686", CodigoISO = "SEN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 208, Nome = "Serra Leoa", CodigoIBGE = "694", CodigoISO = "SLE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 209, Nome = "Sérvia", CodigoIBGE = "688", CodigoISO = "SRB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 210, Nome = "Síria", CodigoIBGE = "760", CodigoISO = "SYR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 211, Nome = "Somália", CodigoIBGE = "706", CodigoISO = "SOM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 212, Nome = "Sri Lanka", CodigoIBGE = "144", CodigoISO = "LKA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 213, Nome = "Suazilândia", CodigoIBGE = "748", CodigoISO = "SWZ", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 214, Nome = "Sudão do Sul", CodigoIBGE = "728", CodigoISO = "SSD", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 215, Nome = "Sudão", CodigoIBGE = "729", CodigoISO = "SDN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 216, Nome = "Suécia", CodigoIBGE = "752", CodigoISO = "SWE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 217, Nome = "Suíça", CodigoIBGE = "756", CodigoISO = "CHE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 218, Nome = "Suriname", CodigoIBGE = "740", CodigoISO = "SUR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 219, Nome = "Svalbard e Jan Mayen Islands", CodigoIBGE = "744", CodigoISO = "SJM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 220, Nome = "Tadjiquistão", CodigoIBGE = "762", CodigoISO = "TJK", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 221, Nome = "Tailândia", CodigoIBGE = "764", CodigoISO = "THA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 222, Nome = "Tanzânia", CodigoIBGE = "834", CodigoISO = "TZA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 223, Nome = "Timor Leste", CodigoIBGE = "626", CodigoISO = "TLS", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 224, Nome = "Togo", CodigoIBGE = "768", CodigoISO = "TGO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 225, Nome = "Tokelau", CodigoIBGE = "772", CodigoISO = "TKL", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 226, Nome = "Tonga", CodigoIBGE = "776", CodigoISO = "TON", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 227, Nome = "Trinidad e Tobago", CodigoIBGE = "780", CodigoISO = "TTO", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 228, Nome = "Tunísia", CodigoIBGE = "788", CodigoISO = "TUN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 229, Nome = "Turcomenistão", CodigoIBGE = "795", CodigoISO = "TKM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 230, Nome = "Turquia", CodigoIBGE = "792", CodigoISO = "TUR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 231, Nome = "Tuvalu", CodigoIBGE = "798", CodigoISO = "TUV", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 232, Nome = "Ucrânia", CodigoIBGE = "804", CodigoISO = "UKR", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 233, Nome = "Uganda", CodigoIBGE = "800", CodigoISO = "UGA", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 234, Nome = "Uruguai", CodigoIBGE = "858", CodigoISO = "URY", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 235, Nome = "Uzbequistão", CodigoIBGE = "860", CodigoISO = "UZB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 236, Nome = "Vanuatu", CodigoIBGE = "548", CodigoISO = "VUT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 237, Nome = "Vaticano", CodigoIBGE = "336", CodigoISO = "VAT", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 238, Nome = "Venezuela", CodigoIBGE = "862", CodigoISO = "VEN", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 239, Nome = "Vietnã", CodigoIBGE = "704", CodigoISO = "VNM", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 240, Nome = "Zâmbia", CodigoIBGE = "894", CodigoISO = "ZMB", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now },
                    new Pais { ID = 241, Nome = "Zimbábue", CodigoIBGE = "716", CodigoISO = "ZWE", DtCadastro = DateTime.Now, DtAtualizado = DateTime.Now }
                );
        }
    }
}
